spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9092   # yahan koi free port daal do (8081, 9090, 9190, etc.)
